### PR TITLE
Fix bugs introduced by new Pitchfork response format

### PR DESCRIPTION
**Pull request by johnwmillr**
This pull request fixes all of the bugs I mentioned in #12 . It passes the unit tests using both python 2 and 3.

### CODE REVIEW

**Comment by johnwmillr** [comment]
The Travis checks failed, but it looks like those issues were already [present in build #35](https://travis-ci.org/michalczaplinski/pitchfork/builds).

**Comment by johnwmillr** [comment]
I've updated the code once again to handle changes in Pitchfork's HTML. I also added a couple of functions for pulling additional information from the page (review abstract and publication date).

The TravisCI errors have to do with running `requirements.txt`; Travis never actually gets to the point of testing the code.

**Comment by fortes** [comment]
Would be great to get this merged in so the package is usable again. Is there anything I can do to help move things along?

**Comment by johnwmillr** [comment]
I'm also hoping to get it merged, but I get the sense that @michalczaplinski is no longer supporting the package. I haven't checked my updates recently, but unless Pitchfork has changed their HTML once again, it should be mostly ready to go (except for the `MultiReview()` class).

**Comment by fortes** [comment]
@johnwmillr Perhaps I'm a bit dense here, but I'm not seeing any failing tests on your branch when running locally via `python3 -m unitteset discover`. I'm able to use it in the REPL.

I believe this is a multi review: https://pitchfork.com/reviews/albums/11639-extraordinary-machine-jon-brion-version-extraordinary-machine/ -- I'm able to find the result, but only the first score is returned.

The CI failure seems to be due to `beautifulsoup4` failing to install correctly.

**Comment by fortes** [comment]
@johnwmillr Looks like it's Python 3.2 that is causing the issue. I changed up the Travis config to restrict to 3.3 or later, and looks like CI passes.

I don't really know python that well, so I've probably done something stupid in my changes to `requirements.txt` and `setup.py`, so feel free to completely ignore them.

Seems like if we just update the travis config we'll get a green build, and we'd be good to merge.

**Comment by fortes** [comment]
Also, it looks like the fork by @tejassharma96 has some newer fixes? https://github.com/tejassharma96/pitchfork

**Comment by johnwmillr** [comment]
Good work with all of this! I don't think you've made any mistakes with the `requirements.txt` file, it looks good to go. 

It also looks like you're right, @tejassharma96 has done plenty of good work on their branch. It does look they've made some substantial deletions to the original branch, I'm not sure what all has been changed.

It seems like it'd be ideal to get all three of our branches merged into the `master` branch, but I think that would have to wait on @michalczaplinski. Any ideas in the meantime?

**Comment by tejassharma96** [comment]
I actually based mine off yours @johnwmillr - needed to use it for a project I was working on so some of the changes might be somewhat specific to that, and I removed a lot of files so that I just had the core functional code. I'm sure all of that could be selectively merged though.

I don't think we're going to be able to get @michalczaplinski to merge it though, I even went as far as to email him but got no response there. One of us could just create an entirely new python package and distribute it though, since he released this under the MIT license.

**Comment by johnwmillr** [comment]
Ha, thank you for weighing in, @tejassharma96! I think you're probably right, I don't expect these changes to get merged to `master` any time soon.

I'm game to start up a new Python package, but I probably wouldn't get to it for a few days. If you or @fortes wants to start one before then, go right ahead. I'd say we should name it `pytchfork`, but it looks like that's taken by a three-year-old [multiprocessing package](https://pypi.org/project/pytchfork/).

**Comment by fortes** [comment]
I suck at python, so I'm just here for the ride. Let me know when something's published and I'll use it!

**Comment by tejassharma96** [comment]
I'll go ahead and give it a crack then. I can add the two of you as contributors if you'd be ok with that? I'm sure any bugs would be worked out a lot faster with 3 heads rather than one :-)

**Comment by tejassharma96** [comment]
https://github.com/tejassharma96/pytchfork-api

**Comment by fortes** [comment]
Sounds great, thanks!

**Comment by johnwmillr** [comment]
Great! My one suggestion would be to call the project `pitchfork_api` rather than `pytchfork_api`. My `pytchfork` suggestion was just a catchy one-word phrase because `pitchfork` is already taken on PyPI. If we're going with a two-word phrase, I think we may as well include "pitchfork" in the name for searchability.

**Comment by tejassharma96** [comment]
Alright, I'll change it up and add both of you.

**Comment by tejassharma96** [comment]
Both of you have been added, if you want to be added to the pypi package too then drop me your usernames there

**Comment by fortes** [comment]
Great, I'm https://pypi.org/user/fortes/ on pypi

**Comment by tejassharma96** [comment]
I can't add you because you don't have a verified email address.

**Comment by johnwmillr** [comment]
Fun! My PyPI username is `johnwmillr`

**Comment by tejassharma96** [comment]
Great, I've added you both and will resend the collab link. I think perhaps it would be a good idea to move to slack to chat now, rather than just chatting on this pull request :)

I've created a chatroom here https://join.slack.com/t/pitchfork-api/shared_invite/enQtNDE4NTQ3NDI5NTcxLTJkYjA2MWJmMjc4NDA4NTBmZTFlYTI1YTE0OWMwMzg2MjlkZTMxODNhNWU0YjNmNGYwNWU0ZTc0OGM2NWEzMjk

**Comment by tejassharma96** [comment]
Actually, just got around to resending the link and it says you are actually a collaborator

**Comment by michalczaplinski** [comment]
@tejassharma96 @johnwmillr @fortes Hi guys! 
Sorry for not replying earlier! I'm kinda surprised and flattered that you guys are actually using this package! I've made it a while ago more as a fun exercise than anything else.

All that being said, I can give you commiter status to the repo if you're interested - I probably won't be too active myself, so you can move things along 🙂

**Comment by fortes** [comment]
@michalczaplinski that would be great if you could add collaborators! Any chance you can add to Pypi so changes can be published? That way we can keep only one published package. Thanks!

**Comment by johnwmillr** [comment]
Thanks for getting back to us, @michalczaplinski! I'm game for being a collaborator on this repository. I agree with @fortes, it'd be convenient to be added as either Maintainers or Owners on Michal's [PyPi package](https://pypi.org/project/pitchfork).

**Comment by michalczaplinski** [comment]
done @johnwmillr @fortes
Give me your pypi usernames, I ll add you there as well. Seriously, thanks for taking the interest. Hit me up if you need anything else! :)

**Comment by fortes** [comment]
@michalczaplinski  I'm `fortes` on pypi: https://pypi.org/user/fortes/

Thanks!

**Comment by johnwmillr** [comment]
My PyPI username is `johnwmillr`. Could you also add @tejassharma96 while you're at it? Their username on PyPI is `tejassharma`.

Thanks!

**Pull request merged**
